"""Code exercises for the modules. The build writes them to assets/exercises.js.

Each exercise: id, title, task (HTML), starter, solution, tests, and optional hint and packages.
A test is [description, Python expression]. The expression runs after the learner's code,
in the same namespace, and must be true.
Run  python tools/check_exercises.py  after a change: each solution must pass all its tests,
and each starter must fail at least one test.
"""

EXERCISES = {
    # ------------------------------------------------------------------ Module 0
    "python-for-ai.html": [
        {"id": "m0-mean", "title": "The mean weight",
         "task": "Complete the function <code>mean_weight(weights)</code>. It must return the mean of the list, rounded to 1 decimal place.",
         "starter": "def mean_weight(weights):\n    # Add all the values, and divide by the number of values\n    return 0\n",
         "solution": "def mean_weight(weights):\n    return round(sum(weights) / len(weights), 1)\n",
         "hint": "Use <code>sum(weights)</code>, <code>len(weights)</code>, and <code>round(value, 1)</code>.",
         "tests": [["mean_weight([262.5, 240.0, 255.5]) is 252.7", "mean_weight([262.5, 240.0, 255.5]) == 252.7"],
                   ["mean_weight([100, 200]) is 150.0", "mean_weight([100, 200]) == 150.0"],
                   ["one value", "mean_weight([310.0]) == 310.0"]]},
        {"id": "m0-large", "title": "Count the large mangoes",
         "task": "Complete <code>count_large(weights, limit)</code>. It must return the number of weights that are equal to the limit or larger. Use a <code>for</code> loop and an <code>if</code> condition.",
         "starter": "def count_large(weights, limit):\n    count = 0\n    for w in weights:\n        pass  # change this line\n    return count\n",
         "solution": "def count_large(weights, limit):\n    count = 0\n    for w in weights:\n        if w >= limit:\n            count = count + 1\n    return count\n",
         "hint": "Inside the loop: <code>if w &gt;= limit:</code>, then add 1 to <code>count</code>.",
         "tests": [["3 of 5 weights are 250 or more", "count_large([262.5, 240.0, 255.5, 310.0, 198.5], 250) == 3"],
                   ["the limit itself counts", "count_large([250, 249], 250) == 1"],
                   ["an empty list gives 0", "count_large([], 250) == 0"]]},
        {"id": "m0-pandas", "title": "The damaged share with pandas",
         "task": "The DataFrame <code>df</code> has a column <code>damaged</code> with 0 or 1. Complete <code>damaged_share(df)</code>. It must return the share of damaged rows, rounded to 2 decimal places.",
         "starter": "import pandas as pd\n\ndef damaged_share(df):\n    return 0\n\ndf = pd.DataFrame({\"variety\": [\"Alphonso\", \"Kesar\", \"Kesar\", \"Totapuri\"], \"damaged\": [0, 1, 0, 1]})\nprint(damaged_share(df))\n",
         "solution": "import pandas as pd\n\ndef damaged_share(df):\n    return round(df[\"damaged\"].mean(), 2)\n\ndf = pd.DataFrame({\"variety\": [\"Alphonso\", \"Kesar\", \"Kesar\", \"Totapuri\"], \"damaged\": [0, 1, 0, 1]})\nprint(damaged_share(df))\n",
         "hint": "The mean of a column of 0 and 1 is the share of 1. Use <code>df[\"damaged\"].mean()</code>.",
         "packages": ["pandas"],
         "tests": [["half of the example is damaged", "damaged_share(df) == 0.5"],
                   ["a different table", "damaged_share(pd.DataFrame({'damaged': [1, 0, 0]})) == 0.33"]]},
    ],
    # ------------------------------------------------------------------ Module 1
    "ai.html": [
        {"id": "m1-next", "title": "Select the next token",
         "task": "A chat AI calculates a probability for each possible next word. Complete <code>next_word(probs)</code>. It must return the word with the highest probability. <code>probs</code> is a dictionary, for example <code>{\"blue\": 0.6, \"grey\": 0.3}</code>.",
         "starter": "def next_word(probs):\n    best = None\n    return best\n",
         "solution": "def next_word(probs):\n    return max(probs, key=probs.get)\n",
         "hint": "Loop over <code>probs.items()</code> and keep the word with the largest value, or use <code>max(probs, key=probs.get)</code>.",
         "tests": [["blue has the highest probability", "next_word({'blue': 0.6, 'grey': 0.3, 'dark': 0.1}) == 'blue'"],
                   ["the order of the dictionary does not matter", "next_word({'a': 0.1, 'b': 0.2, 'c': 0.7}) == 'c'"]]},
        {"id": "m1-learn", "title": "One step of learning",
         "task": "Training is a loop: guess, compare, adjust. Complete <code>adjust(weight, guess, correct, rate)</code>. It must return <code>weight - rate * (guess - correct)</code>: a guess that is too high makes the weight smaller.",
         "starter": "def adjust(weight, guess, correct, rate):\n    error = 0  # compare the guess with the correct answer\n    return weight\n",
         "solution": "def adjust(weight, guess, correct, rate):\n    error = guess - correct\n    return weight - rate * error\n",
         "hint": "The error is <code>guess - correct</code>. Then return <code>weight - rate * error</code>.",
         "tests": [["a guess that is too high decreases the weight", "abs(adjust(1.0, 12, 10, 0.1) - 0.8) < 1e-9"],
                   ["a guess that is too low increases the weight", "abs(adjust(1.0, 8, 10, 0.1) - 1.2) < 1e-9"],
                   ["a correct guess changes nothing", "adjust(2.5, 10, 10, 0.1) == 2.5"]]},
    ],
    # ------------------------------------------------------------------ Module 2
    "mathematics.html": [
        {"id": "m2-std", "title": "The standard deviation",
         "task": "Complete <code>std_dev(values)</code>: the square root of the mean of the squared differences from the mean (divide by n). Do not use a library.",
         "starter": "def std_dev(values):\n    mean = sum(values) / len(values)\n    return 0\n",
         "solution": "def std_dev(values):\n    mean = sum(values) / len(values)\n    return (sum((x - mean) ** 2 for x in values) / len(values)) ** 0.5\n",
         "hint": "<code>(sum((x - mean) ** 2 for x in values) / len(values)) ** 0.5</code>",
         "tests": [["std_dev([2, 4, 4, 4, 5, 5, 7, 9]) is 2", "abs(std_dev([2, 4, 4, 4, 5, 5, 7, 9]) - 2) < 1e-9"],
                   ["equal values give 0", "std_dev([5, 5, 5]) == 0"]]},
        {"id": "m2-bayes", "title": "Bayes' rule",
         "task": "Complete <code>bayes(p_b_given_a, p_a, p_b)</code>. It must return P(A | B) = P(B | A) &times; P(A) &divide; P(B).",
         "starter": "def bayes(p_b_given_a, p_a, p_b):\n    return 0\n",
         "solution": "def bayes(p_b_given_a, p_a, p_b):\n    return p_b_given_a * p_a / p_b\n",
         "tests": [["0.9 x 0.01 / 0.05 = 0.18", "abs(bayes(0.9, 0.01, 0.05) - 0.18) < 1e-9"],
                   ["P(B | A) = 1 and P(A) = P(B) gives 1", "abs(bayes(1, 0.2, 0.2) - 1) < 1e-9"]]},
        {"id": "m2-softmax", "title": "Softmax",
         "task": "Complete <code>softmax(scores)</code>. It must return a list of probabilities: e to the power of each score, divided by the sum of all of them. Use <code>math.exp</code>.",
         "starter": "import math\n\ndef softmax(scores):\n    return scores\n",
         "solution": "import math\n\ndef softmax(scores):\n    exps = [math.exp(s) for s in scores]\n    total = sum(exps)\n    return [e / total for e in exps]\n",
         "hint": "Make <code>exps = [math.exp(s) for s in scores]</code>, then divide each by <code>sum(exps)</code>.",
         "tests": [["the probabilities add up to 1", "abs(sum(softmax([2.0, 1.0, 0.1])) - 1) < 1e-9"],
                   ["the largest score gets the largest probability", "softmax([2.0, 1.0, 0.1])[0] > softmax([2.0, 1.0, 0.1])[1]"],
                   ["equal scores give equal probabilities", "all(abs(p - 1/3) < 1e-9 for p in softmax([1, 1, 1]))"]]},
    ],
    # ------------------------------------------------------------------ Module 3
    "machine-learning.html": [
        {"id": "m3-pr", "title": "Precision and recall",
         "task": "Complete <code>precision_recall(tp, fp, fn)</code>. It must return a tuple (precision, recall), each rounded to 2 decimal places.",
         "starter": "def precision_recall(tp, fp, fn):\n    precision = 0\n    recall = 0\n    return round(precision, 2), round(recall, 2)\n",
         "solution": "def precision_recall(tp, fp, fn):\n    precision = tp / (tp + fp)\n    recall = tp / (tp + fn)\n    return round(precision, 2), round(recall, 2)\n",
         "hint": "Precision = TP / (TP + FP). Recall = TP / (TP + FN).",
         "tests": [["the spam filter of Figure 9: 40, 5, 10", "precision_recall(40, 5, 10) == (0.89, 0.8)"],
                   ["no errors gives (1.0, 1.0)", "precision_recall(5, 0, 0) == (1.0, 1.0)"]]},
        {"id": "m3-step", "title": "One step of gradient descent",
         "task": "The loss is (w &minus; 3)&sup2;. Its slope is 2(w &minus; 3). Complete <code>step(w, rate)</code>: return the new weight after one step of gradient descent. Then <code>train()</code> runs 50 steps from w = 0.",
         "starter": "def step(w, rate):\n    slope = 2 * (w - 3)\n    return w\n\ndef train():\n    w = 0.0\n    for _ in range(50):\n        w = step(w, 0.1)\n    return w\n",
         "solution": "def step(w, rate):\n    slope = 2 * (w - 3)\n    return w - rate * slope\n\ndef train():\n    w = 0.0\n    for _ in range(50):\n        w = step(w, 0.1)\n    return w\n",
         "hint": "Move opposite to the slope: <code>w - rate * slope</code>.",
         "tests": [["one step from 0 with rate 0.1 gives 0.6", "abs(step(0.0, 0.1) - 0.6) < 1e-9"],
                   ["after 50 steps, w is near 3, the bottom of the loss", "abs(train() - 3) < 0.01"]]},
        {"id": "m3-sklearn", "title": "Train and test a model",
         "task": "Complete the code: divide the data with <code>train_test_split</code> (test_size=0.25, random_state=0), train a <code>DecisionTreeClassifier(random_state=0)</code>, and save the test accuracy in <code>accuracy</code>.",
         "starter": "from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\n\nX, y = load_iris(return_X_y=True)\naccuracy = 0\nprint(accuracy)\n",
         "solution": "from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\n\nX, y = load_iris(return_X_y=True)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)\nmodel = DecisionTreeClassifier(random_state=0).fit(X_train, y_train)\naccuracy = model.score(X_test, y_test)\nprint(accuracy)\n",
         "hint": "<code>model = DecisionTreeClassifier(random_state=0).fit(X_train, y_train)</code>, then <code>model.score(X_test, y_test)</code>.",
         "packages": ["scikit-learn"],
         "tests": [["the test set has 38 examples", "len(y_test) == 38"],
                   ["the accuracy is more than 0.9", "accuracy > 0.9"]]},
    ],
    # ------------------------------------------------------------------ Module 4
    "deep-learning.html": [
        {"id": "m4-neuron", "title": "A neuron",
         "task": "Complete <code>neuron(inputs, weights, bias)</code>: multiply each input by its weight, add the results and the bias, and apply ReLU (negative values become 0).",
         "starter": "def neuron(inputs, weights, bias):\n    total = 0\n    return total\n",
         "solution": "def neuron(inputs, weights, bias):\n    total = sum(x * w for x, w in zip(inputs, weights)) + bias\n    return max(0, total)\n",
         "hint": "<code>sum(x * w for x, w in zip(inputs, weights)) + bias</code>, then <code>max(0, total)</code>.",
         "tests": [["1x0.5 + 2x0.25 + 0.1 = 1.1", "abs(neuron([1, 2], [0.5, 0.25], 0.1) - 1.1) < 1e-9"],
                   ["a negative sum gives 0 (ReLU)", "neuron([1, 1], [-1, -1], 0) == 0"]]},
        {"id": "m4-cosine", "title": "Similar embeddings",
         "task": "Complete <code>cosine(a, b)</code>: the dot product divided by the product of the two lengths. Use NumPy.",
         "starter": "import numpy as np\n\ndef cosine(a, b):\n    a, b = np.array(a), np.array(b)\n    return 0\n",
         "solution": "import numpy as np\n\ndef cosine(a, b):\n    a, b = np.array(a), np.array(b)\n    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b)))\n",
         "hint": "<code>a @ b</code> is the dot product. <code>np.linalg.norm(a)</code> is the length.",
         "packages": ["numpy"],
         "tests": [["the same direction gives 1", "abs(cosine([1, 2], [2, 4]) - 1) < 1e-9"],
                   ["a right angle gives 0", "abs(cosine([1, 0], [0, 1])) < 1e-9"],
                   ["opposite directions give -1", "abs(cosine([1, 1], [-1, -1]) + 1) < 1e-9"]]},
    ],
    # ------------------------------------------------------------------ Module 5
    "generative-ai.html": [
        {"id": "m5-temp", "title": "Temperature",
         "task": "Complete <code>with_temperature(scores, t)</code>: divide each score by the temperature <code>t</code>, then apply softmax. A low temperature makes the largest probability larger.",
         "starter": "import math\n\ndef with_temperature(scores, t):\n    exps = [math.exp(s) for s in scores]\n    return [e / sum(exps) for e in exps]\n",
         "solution": "import math\n\ndef with_temperature(scores, t):\n    exps = [math.exp(s / t) for s in scores]\n    return [e / sum(exps) for e in exps]\n",
         "hint": "Change <code>math.exp(s)</code> to <code>math.exp(s / t)</code>.",
         "tests": [["a low temperature: the top word gets more than 0.95", "with_temperature([3.0, 1.8, 1.4], 0.2)[0] > 0.95"],
                   ["a high temperature (3): the top word gets less than 0.5", "with_temperature([3.0, 1.8, 1.4], 3.0)[0] < 0.5"]]},
        {"id": "m5-prompt", "title": "A prompt template",
         "task": "Complete <code>make_prompt(task, context, fmt)</code>. Return one text with three lines: <code>Task: ...</code>, <code>Context: ...</code>, and <code>Format: ...</code>, in this order.",
         "starter": "def make_prompt(task, context, fmt):\n    return task\n",
         "solution": "def make_prompt(task, context, fmt):\n    return f\"Task: {task}\\nContext: {context}\\nFormat: {fmt}\"\n",
         "hint": "Use an f-string with <code>\\n</code> between the lines.",
         "tests": [["the three lines are there, in order",
                    "make_prompt('Explain ripening', 'For farmers', '5 bullet points') == 'Task: Explain ripening\\nContext: For farmers\\nFormat: 5 bullet points'"]]},
    ],
    # ------------------------------------------------------------------ Module 6
    "responsible-ai.html": [
        {"id": "m6-groups", "title": "Recall for each group",
         "task": "Each record is (group, real, predicted), with 1 = damaged. Complete <code>recall_by_group(records)</code>: return a dictionary with the recall of each group, rounded to 2 decimal places. Different results for groups can show bias.",
         "starter": "def recall_by_group(records):\n    result = {}\n    return result\n",
         "solution": "def recall_by_group(records):\n    result = {}\n    for g in sorted({r[0] for r in records}):\n        real = [r for r in records if r[0] == g and r[1] == 1]\n        found = [r for r in real if r[2] == 1]\n        result[g] = round(len(found) / len(real), 2) if real else 0.0\n    return result\n",
         "hint": "For each group, take the records with real = 1. Recall = the number with predicted = 1 divided by that number.",
         "tests": [["farm A 2 of 2, farm B 1 of 3",
                    "recall_by_group([('A',1,1),('A',1,1),('A',0,0),('B',1,1),('B',1,0),('B',1,0)]) == {'A': 1.0, 'B': 0.33}"]]},
        {"id": "m6-privacy", "title": "Remove phone numbers",
         "task": "Data minimization: complete <code>clean(text)</code>. It must change each 10-digit number into <code>[phone]</code>. Use the module <code>re</code>.",
         "starter": "import re\n\ndef clean(text):\n    return text\n",
         "solution": "import re\n\ndef clean(text):\n    return re.sub(r\"\\b\\d{10}\\b\", \"[phone]\", text)\n",
         "hint": "<code>re.sub(r\"\\b\\d{10}\\b\", \"[phone]\", text)</code>",
         "tests": [["one number", "clean('Call 9876543210 now') == 'Call [phone] now'"],
                   ["shorter numbers stay", "clean('Box 12 of 40') == 'Box 12 of 40'"]]},
    ],
    # ------------------------------------------------------------------ Module 7
    "ai-in-practice.html": [
        {"id": "m7-baseline", "title": "The baseline",
         "task": "Complete <code>baseline_accuracy(labels)</code>: the accuracy of a model that always predicts the most frequent label, rounded to 3 decimal places.",
         "starter": "def baseline_accuracy(labels):\n    return 0\n",
         "solution": "def baseline_accuracy(labels):\n    most = max(set(labels), key=labels.count)\n    return round(labels.count(most) / len(labels), 3)\n",
         "hint": "Find the most frequent label with <code>max(set(labels), key=labels.count)</code>.",
         "tests": [["4,825 ham and 747 spam give 0.866", "baseline_accuracy(['ham'] * 4825 + ['spam'] * 747) == 0.866"],
                   ["two equal groups give 0.5", "baseline_accuracy([0, 1, 0, 1]) == 0.5"]]},
        {"id": "m7-onehot", "title": "One-hot encoding",
         "task": "Complete <code>one_hot(value, categories)</code>. It must return a list with 1 at the place of the value and 0 at the other places.",
         "starter": "def one_hot(value, categories):\n    return []\n",
         "solution": "def one_hot(value, categories):\n    return [1 if c == value else 0 for c in categories]\n",
         "tests": [["Kesar in three types", "one_hot('Kesar', ['Alphonso', 'Kesar', 'Totapuri']) == [0, 1, 0]"],
                   ["the first type", "one_hot('Alphonso', ['Alphonso', 'Kesar']) == [1, 0]"]]},
        {"id": "m7-drift", "title": "Find drift",
         "task": "Complete <code>drift_alert(train_values, new_values, limit)</code>. Return True if the mean of the new values is more than <code>limit</code> standard deviations of the training values from the training mean.",
         "starter": "def drift_alert(train_values, new_values, limit):\n    m = sum(train_values) / len(train_values)\n    s = (sum((x - m) ** 2 for x in train_values) / len(train_values)) ** 0.5\n    return False\n",
         "solution": "def drift_alert(train_values, new_values, limit):\n    m = sum(train_values) / len(train_values)\n    s = (sum((x - m) ** 2 for x in train_values) / len(train_values)) ** 0.5\n    new_mean = sum(new_values) / len(new_values)\n    return abs(new_mean - m) > limit * s\n",
         "hint": "Calculate the mean of <code>new_values</code>, then compare <code>abs(new_mean - m)</code> with <code>limit * s</code>.",
         "tests": [["the new camera sees fewer spots: alert", "drift_alert([1, 2, 1, 2, 3, 1], [0, 0, 0, 0], 1)"],
                   ["similar data: no alert", "not drift_alert([1, 2, 1, 2, 3, 1], [1, 2, 2, 1], 1)"]]},
    ],
    # ------------------------------------------------------------------ Module 8
    "devops.html": [
        {"id": "m8-validate", "title": "Check the API input",
         "task": "Complete <code>errors(mango)</code>. Return a list of error texts: <code>\"weight\"</code> if <code>weight_g</code> is not between 0 and 1000 (0 not allowed), and <code>\"firmness\"</code> if <code>firmness</code> is not between 0 and 10. A good input gives an empty list.",
         "starter": "def errors(mango):\n    found = []\n    return found\n",
         "solution": "def errors(mango):\n    found = []\n    if not 0 < mango[\"weight_g\"] < 1000:\n        found.append(\"weight\")\n    if not 0 <= mango[\"firmness\"] <= 10:\n        found.append(\"firmness\")\n    return found\n",
         "hint": "Python can compare in a chain: <code>0 &lt; x &lt; 1000</code>.",
         "tests": [["a good mango", "errors({'weight_g': 260, 'firmness': 7}) == []"],
                   ["a weight of -5", "errors({'weight_g': -5, 'firmness': 7}) == ['weight']"],
                   ["two errors", "errors({'weight_g': 0, 'firmness': 11}) == ['weight', 'firmness']"]]},
        {"id": "m8-slo", "title": "The error budget",
         "task": "Complete <code>allowed_minutes(slo_percent, days)</code>: the minutes without service that the SLO allows in that number of days, rounded to 1 decimal place.",
         "starter": "def allowed_minutes(slo_percent, days):\n    return 0\n",
         "solution": "def allowed_minutes(slo_percent, days):\n    return round(days * 24 * 60 * (100 - slo_percent) / 100, 1)\n",
         "hint": "Total minutes &times; (100 &minus; SLO) &divide; 100.",
         "tests": [["99.9% in 30 days is 43.2 minutes", "allowed_minutes(99.9, 30) == 43.2"],
                   ["99% in 30 days is 432 minutes", "allowed_minutes(99, 30) == 432.0"]]},
    ],
    # ------------------------------------------------------------------ Module 9
    "llm-engineering.html": [
        {"id": "m9-chunk", "title": "Divide a document into chunks",
         "task": "Complete <code>chunk(text, size, overlap)</code>. Return a list of chunks of <code>size</code> words. Each chunk starts <code>size - overlap</code> words after the previous one. Stop when the rest of the text is already in the last chunk.",
         "starter": "def chunk(text, size, overlap):\n    words = text.split()\n    return [text]\n",
         "solution": "def chunk(text, size, overlap):\n    words = text.split()\n    step = size - overlap\n    return [\" \".join(words[i:i + size]) for i in range(0, max(len(words) - overlap, 1), step)]\n",
         "hint": "Use <code>range(0, max(len(words) - overlap, 1), size - overlap)</code> and join <code>words[i:i + size]</code>.",
         "tests": [["10 words, size 4, overlap 1: 3 chunks", "chunk('a b c d e f g h i j', 4, 1) == ['a b c d', 'd e f g', 'g h i j']"],
                   ["a short text gives one chunk", "chunk('one two', 4, 1) == ['one two']"]]},
        {"id": "m9-recall", "title": "Recall at k",
         "task": "Complete <code>recall_at_k(results, expected, k)</code>. <code>results</code> is a list of lists of file names (one list for each question), and <code>expected</code> is the correct file for each question. Return the share of questions with the correct file in the first k results.",
         "starter": "def recall_at_k(results, expected, k):\n    hits = 0\n    return hits\n",
         "solution": "def recall_at_k(results, expected, k):\n    hits = sum(e in r[:k] for r, e in zip(results, expected))\n    return hits / len(expected)\n",
         "hint": "For each pair, check <code>e in r[:k]</code>. Count the hits, then divide by the number of questions.",
         "tests": [["2 of 3 at k = 1", "abs(recall_at_k([['a', 'b'], ['b', 'a'], ['c', 'a']], ['a', 'a', 'c'], 1) - 2/3) < 1e-9"],
                   ["3 of 3 at k = 2", "recall_at_k([['a', 'b'], ['b', 'a'], ['c', 'a']], ['a', 'a', 'c'], 2) == 1.0"]]},
        {"id": "m9-guard", "title": "A guardrail for refunds",
         "task": "Complete <code>check_refund(amount, paid, approved)</code>. Return <code>\"ok\"</code> only if 0 &lt; amount &le; paid and a person approved. Else return <code>\"amount\"</code> for a wrong amount, or <code>\"approval\"</code> if the amount is good but nobody approved.",
         "starter": "def check_refund(amount, paid, approved):\n    return \"ok\"\n",
         "solution": "def check_refund(amount, paid, approved):\n    if not 0 < amount <= paid:\n        return \"amount\"\n    if not approved:\n        return \"approval\"\n    return \"ok\"\n",
         "hint": "Check the amount first, then the approval.",
         "tests": [["a good, approved refund", "check_refund(1800, 9000, True) == 'ok'"],
                   ["too much money", "check_refund(99999, 9000, True) == 'amount'"],
                   ["no approval", "check_refund(1800, 9000, False) == 'approval'"],
                   ["a negative amount", "check_refund(-5, 9000, True) == 'amount'"]]},
    ],
}
